# Kong Reference
kong:
  host: "http://kong:8001"
  consumer_request: "/consumers/"
  jwt_request: "/consumers/%s/jwt"

#Mysql
mysql:
  host: db
  port: 3306
  user: root
  password:
  database: userdb
