version: "3.8"

services:
  user:
    image: restore/user:latest
    deploy:
      replicas: 3
    networks:
      main:
        aliases:
          - user
    depends_on:
      - db

networks:
  main:
    external: true